name: Playwright Java Tests

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Cache Maven dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-m2

      - name: Install dependencies & compile
        run: mvn clean compile test-compile

      - name: Install Playwright Browsers
        run: mvn exec:java -e -Dexec.mainClass=com.microsoft.playwright.CLI -Dexec.args="install"

      - name: Run Regression Tests
        run: mvn test -DsuiteXmlFile=src/test/resources/testrunners/testng_regression.xml
        
      - name: Run Smoke Tests
        run: mvn test -DsuiteXmlFile=src/test/resources/testrunners/testng_smoke.xml
        
      - name: Run Full Suite
        run: mvn test -DsuiteXmlFile=src/test/resources/testrunners/testng_suite.xml  

      - name: Upload Extent Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: extent-report
          path: |
            build/TestExecutionReport.html
            test-output/
            target/surefire-reports/
          if-no-files-found: warn
          retention-days: 30
